// Code generated by "stringer -output parser_string.go -type=NodeType"; DO NOT EDIT.

package sexp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NodeNil-0]
	_ = x[NodeSymbol-1]
	_ = x[NodeInt-2]
	_ = x[NodeString-3]
	_ = x[NodeCell-4]
}

const _NodeType_name = "NodeNilNodeSymbolNodeIntNodeStringNodeCell"

var _NodeType_index = [...]uint8{0, 7, 17, 24, 34, 42}

func (i NodeType) String() string {
	if i < 0 || i >= NodeType(len(_NodeType_index)-1) {
		return "NodeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodeType_name[_NodeType_index[i]:_NodeType_index[i+1]]
}
